[package]
name = "pest-calculator"
version = "0.1.1"
edition = "2021"
rust-version = "1.76"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
pest = "2.7"
pest_derive = "2.7"
